server:
  tomcat:
    uri-encoding: UTF-8
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: local
  freemarker:
    template-loader-path: classpath:/templates/
  messages:
    basename: messages,config.i18n.messages
    always-use-message-format: false
    cache-duration:
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: clustercfg.wowlibre.tkfyma.use2.cache.amazonaws.com
      port: 6379
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/accounts
    username: root
    password: Wowlibre96@@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'mschitiva68@gmail.com'
    password: 'mfbv fjfc eond lzhc'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: 'UTF-8'
aws:
  ses:
    access-key: AKIAS6J7QIAW6ZIQPH3X
    secret-key: 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
    region: us-east-1
    from-email: wowlibrecomunidad@gmail.com
server:
  servlet:
    context-path: /core
  address: 0.0.0.0
  port: 8091
application:
  host:
    wow-libre: http://localhost:3000
  security:
    mail:
      api-key: 'mlsn.0ebc57351a0ce3a6b78a6e2e80f0233d8b826f34cdccc052e3946909de563769'
    jwt:
      secret-key: 6E4D574873506B4A72434B6A614B39786F736B7855666B4D456A6E466F785572
      expiration: 604800000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
management:
  endpoints:
    web:
      exposure:
        include: health
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${REDIS-URL}
      port: ${REDIS-PORT}
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: 'smtp-relay.brevo.com'
    port: 587
    username: '7e339a001@smtp-brevo.com'
    password: 'RyfB7JX3E0YIcktG'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
    default-encoding: UTF-8
aws:
  ses:
    access-key: AKIAS6J7QIAW6ZIQPH3X
    secret-key: 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
    region: us-east-1
    from-email: wowlibrecomunidad@gmail.com
server:
  servlet:
    context-path: /core
  address: 0.0.0.0
  port: 8091
application:
  host:
    wow-libre: ${WOW_LIBRE_HOST}
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # a day
      refresh-token:
        expiration: 604800000 # 7 days