spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
      allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/accounts
    username: root
    password: Loquendo96@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'mschitiva68@gmail.com'
    password: 'xxvl spfa sdal bzgm'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  address: 0.0.0.0
  port: 8090
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days